language: scala

scala:
  - 2.10.4
#  - 2.11.0-RC3

jdk:
  - oraclejdk8
#  - openjdk8
  - oraclejdk7
  - openjdk7
  - openjdk6

matrix:
  fast_finish: true
  allow_failures:
    - jdk: oraclejdk8
    - jdk: openjdk8

#script: "sbt 'project akka-tracing-core' 'coveralls'"
