language: scala

scala:
  - 2.10.4
  - 2.11.0

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6

matrix:
  fast_finish: true
#  allow_failures:
#    - jdk: oraclejdk8

cache:
  directories:
  - $HOME/.ivy2

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq thrift-compiler

#script: "sbt 'project akka-tracing-core' 'coveralls'"
